#!/bin/bash

set -e

#./build_cp_fw
./build_lin
./build_win
./build_android

rm /storage/mnt_webserver/web/ubercart_downloads/openroad_tool_*
mv build/lin/openroad_tool_* /storage/mnt_webserver/web/ubercart_downloads/
mv build/win/openroad_tool_* /storage/mnt_webserver/web/ubercart_downloads/
mv build/android/openroad_tool_* /storage/mnt_webserver/web/ubercart_downloads/

